<a href="https://colab.research.google.com/github/UurZer/Cat-And-Dog-Classification/blob/main/Cat_and_dog_Classfication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from numpy import genfromtxt
my_data=genfromtxt('/content/2. soru.csv',delimiter=',')

In [8]:
my_data

array([[4.  , 3.6 , 0.  ],
       [4.  , 3.7 , 0.  ],
       [4.  , 3.8 , 0.  ],
       [4.  , 3.9 , 0.  ],
       [4.  , 4.  , 0.  ],
       [4.  , 4.1 , 0.  ],
       [4.  , 4.2 , 0.  ],
       [4.  , 4.3 , 0.  ],
       [4.  , 4.4 , 0.  ],
       [4.  , 4.5 , 0.  ],
       [4.  , 4.  , 0.  ],
       [4.  , 3.4 , 0.  ],
       [4.  , 3.5 , 0.  ],
       [4.  , 3.3 , 0.  ],
       [4.  , 3.  , 0.  ],
       [2.  , 0.5 , 1.  ],
       [2.  , 0.8 , 1.  ],
       [2.  , 0.9 , 1.  ],
       [2.  , 1.  , 1.  ],
       [2.  , 1.1 , 1.  ],
       [2.  , 1.  , 1.  ],
       [2.  , 1.2 , 1.  ],
       [2.  , 1.3 , 1.  ],
       [2.  , 1.4 , 1.  ],
       [2.  , 1.5 , 1.  ],
       [2.  , 1.6 , 1.  ],
       [2.  , 1.7 , 1.  ],
       [2.  , 1.8 , 1.  ],
       [2.  , 1.9 , 1.  ],
       [2.  , 1.65, 1.  ],
       [2.  , 1.75, 1.  ]])

In [9]:
my_data.shape#31 tane veri var ve her verinin 3 özelliği var(ayak sayısı,kilo,sınıf)

(31, 3)

In [10]:
x=my_data[:,0:2]#Özellikler
y=my_data[:,2]#Sınıflar olarak data mızı 2 ye ayırdık

In [11]:
x#Özelliklerimiz

array([[4.  , 3.6 ],
       [4.  , 3.7 ],
       [4.  , 3.8 ],
       [4.  , 3.9 ],
       [4.  , 4.  ],
       [4.  , 4.1 ],
       [4.  , 4.2 ],
       [4.  , 4.3 ],
       [4.  , 4.4 ],
       [4.  , 4.5 ],
       [4.  , 4.  ],
       [4.  , 3.4 ],
       [4.  , 3.5 ],
       [4.  , 3.3 ],
       [4.  , 3.  ],
       [2.  , 0.5 ],
       [2.  , 0.8 ],
       [2.  , 0.9 ],
       [2.  , 1.  ],
       [2.  , 1.1 ],
       [2.  , 1.  ],
       [2.  , 1.2 ],
       [2.  , 1.3 ],
       [2.  , 1.4 ],
       [2.  , 1.5 ],
       [2.  , 1.6 ],
       [2.  , 1.7 ],
       [2.  , 1.8 ],
       [2.  , 1.9 ],
       [2.  , 1.65],
       [2.  , 1.75]])

In [12]:
y#Sınıflarımız

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
x[0].shape

(2,)

In [20]:
from keras import models
from keras import layers

network =models.Sequential()
network.add(layers.Dense(12,activation='relu' ,input_shape=(2,)))
network.add(layers.Dense(1,activation='sigmoid'))
network.compile(optimizer='rmsprop',
                loss="binary_crossentropy",
                metrics=['accuracy'])
network.fit(x,y,epochs=150,batch_size=10)

Epoch 1/150
4/4 [==============================] - 13s 4ms/step - loss: 0.8239 - accuracy: 0.5031
Epoch 2/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7710 - accuracy: 0.5631
Epoch 3/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7725 - accuracy: 0.5365
Epoch 4/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7945 - accuracy: 0.4465
Epoch 5/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7809 - accuracy: 0.4765
Epoch 6/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7506 - accuracy: 0.5565
Epoch 7/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7458 - accuracy: 0.5531
Epoch 8/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7503 - accuracy: 0.4965
Epoch 9/150
4/4 [==============================] - 0s 5ms/step - loss: 0.7467 - accuracy: 0.4931
Epoch 10/150
4/4 [==============================] - 0s 4ms/step - loss: 0.7272 - accuracy: 0.5431
Epoch 11/150
4/4 [==========

In [21]:
my_test_data=genfromtxt('/content/2. soru Test.csv',delimiter=',')

In [22]:
x_test=my_test_data[:,0:2]#Özellikler
y_test=my_test_data[:,2]#Sınıflar olarak data mızı 2 ye ayırdık

In [26]:
#Tabi benim oluşturduğum test dataseti önceki verilere benzer olduduğu için
#başarı ölçütü train'e göre daha başarılı çıktı.
test_loss,test_acc=network.evaluate(x_test,y_test)

1/1 [==============================] - 0s 16ms/step - loss: 0.3137 - accuracy: 0.9048
